// 멤버 명단. 기수 조사(노션) 데이터를 옮겼고, API 명세가 확정되면 이 함수 안만 fetch(ISR)로 바꿔요.
// id는 서버 id가 나올 때까지 이름을 그대로 써요. 사진은 깃허브 아바타(github.com/유저명.png)를 써요.
// 자기소개(intro)는 이력에 맞춰 임의로 넣은 임시 문구예요. 본인이 보내주는 대로 바꿔요.
import type { Member } from "./model";

const MEMBERS: Member[] = [
  {
    id: "김범수",
    name: "김범수",
    affiliation: "창립 멤버",
    role: "운영진",
    intro: "그리디를 처음 만들었고, 지금도 운영진으로 함께하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기", "3기", "4기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/Indigochi1d",
    photoUrl: "https://github.com/Indigochi1d.png",
    history: [{ cohort: "4기", title: "운영진 · 프론트엔드 리드 · 프론트엔드 리뷰어" }, { cohort: "3기", title: "프론트엔드 리뷰어" }, { cohort: "2기", title: "운영진 · 프론트엔드 리드 · 프론트엔드 리뷰어" }, { cohort: "1기", title: "운영진 · 프론트엔드 리드 · 프론트엔드 리뷰어" }, { cohort: "창립", title: "창립 멤버" }],
  },
  {
    id: "신혜빈",
    name: "신혜빈",
    affiliation: "1기 BE",
    role: "운영진",
    intro: "1기 백엔드로 시작해 지금은 운영진으로 함께하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "3기", "4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/c0mpuTurtle",
    photoUrl: "https://github.com/c0mpuTurtle.png",
    history: [{ cohort: "4기", title: "운영진 · 백엔드 리뷰어" }, { cohort: "3기", title: "백엔드 리드 · 백엔드 리뷰어" }, { cohort: "1기", title: "백엔드 멤버" }],
  },
  {
    id: "정상희",
    name: "정상희",
    affiliation: "1기 BE",
    role: "운영진",
    intro: "1기 백엔드로 시작해 지금은 그리디를 이끌고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기", "3기", "4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/SANGHEEJEONG",
    photoUrl: "https://github.com/SANGHEEJEONG.png",
    history: [{ cohort: "4기", title: "회장 · 운영진 · 백엔드 리드" }, { cohort: "3기", title: "백엔드 리드 · 백엔드 리뷰어" }, { cohort: "2기", title: "백엔드 리드" }, { cohort: "1기", title: "백엔드 멤버" }],
  },
  {
    id: "정창우",
    name: "정창우",
    affiliation: "2기 FE",
    role: "운영진",
    intro: "2기 프론트엔드로 시작해 지금은 운영진으로 함께하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["2기", "4기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/ChangwooJ",
    photoUrl: "https://github.com/ChangwooJ.png",
    history: [{ cohort: "4기", title: "운영진 · 프론트엔드 리드 · 프론트엔드 리뷰어" }, { cohort: "2기", title: "프론트엔드 멤버" }],
  },
  {
    id: "박찬빈",
    name: "박찬빈",
    affiliation: "2기 FE",
    role: "운영진",
    intro: "2기 프론트엔드로 시작해 지금은 운영진으로 함께하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["2기", "3기", "4기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/INSANE-P",
    photoUrl: "https://github.com/INSANE-P.png",
    history: [{ cohort: "4기", title: "운영진 · 프론트엔드 리드 · 프론트엔드 리뷰어" }, { cohort: "3기", title: "프론트엔드 리드" }, { cohort: "2기", title: "프론트엔드 멤버" }],
  },
  {
    id: "황혜림",
    name: "황혜림",
    affiliation: "2기 BE",
    role: "운영진",
    intro: "2기 백엔드로 시작해 지금은 운영진으로 함께하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["2기", "4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/HyerimH",
    photoUrl: "https://github.com/HyerimH.png",
    history: [{ cohort: "4기", title: "운영진" }, { cohort: "2기", title: "백엔드 멤버" }],
  },
  {
    id: "심혁",
    name: "심혁",
    affiliation: "3기 FE",
    role: "운영진",
    intro: "3기 프론트엔드로 시작해 지금은 운영진으로 함께하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["3기", "4기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/johncakes",
    photoUrl: "https://github.com/johncakes.png",
    history: [{ cohort: "4기", title: "운영진 · 프론트엔드 리드" }, { cohort: "3기", title: "프론트엔드 멤버" }],
  },
  {
    id: "윤재홍",
    name: "윤재홍",
    affiliation: "3기 FE",
    role: "운영진",
    intro: "3기 프론트엔드로 시작해 지금은 운영진으로 함께하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["3기", "4기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/yoonjaehong26",
    photoUrl: "https://github.com/yoonjaehong26.png",
    history: [{ cohort: "4기", title: "운영진 · 프론트엔드 리드" }, { cohort: "3기", title: "프론트엔드 멤버" }],
  },
  {
    id: "김민기",
    name: "김민기",
    affiliation: "4기 영입",
    role: "운영진",
    intro: "4기에 합류해 그리디 운영을 함께하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/supernovaMK",
    photoUrl: "https://github.com/supernovaMK.png",
    history: [{ cohort: "4기", title: "운영진 · 백엔드 리뷰어" }],
  },
  {
    id: "이진",
    name: "이진",
    affiliation: "4기 영입",
    role: "운영진",
    intro: "4기에 합류해 그리디 운영을 함께하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/2Jin1031",
    photoUrl: "https://github.com/2Jin1031.png",
    history: [{ cohort: "4기", title: "운영진 · 백엔드 리뷰어" }],
  },
  {
    id: "김수민",
    name: "김수민",
    affiliation: "창립 멤버",
    role: "리뷰어",
    intro: "그리디를 처음 만들었고, 지금은 리뷰어로 후배들의 코드를 함께 다듬어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기", "3기", "4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/boyekim",
    photoUrl: "https://github.com/boyekim.png",
    history: [{ cohort: "4기", title: "백엔드 리뷰어" }, { cohort: "3기", title: "운영진" }, { cohort: "2기", title: "운영진" }, { cohort: "1기", title: "운영진" }, { cohort: "창립", title: "창립 멤버" }],
  },
  {
    id: "송혜정",
    name: "송혜정",
    affiliation: "1기 FE",
    role: "리뷰어",
    intro: "1기 프론트엔드 출신이고, 지금은 리뷰어로 후배들의 코드를 함께 다듬어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기", "3기", "4기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/Songhyejeong",
    photoUrl: "https://github.com/Songhyejeong.png",
    history: [{ cohort: "4기", title: "프론트엔드 리뷰어" }, { cohort: "3기", title: "운영진 · 프론트엔드 리드 · 프론트엔드 리뷰어" }, { cohort: "2기", title: "운영진 · 프론트엔드 리드 · 프론트엔드 리뷰어" }, { cohort: "1기", title: "프론트엔드 멤버" }],
  },
  {
    id: "남해윤",
    name: "남해윤",
    affiliation: "1기 BE",
    role: "리뷰어",
    intro: "1기 백엔드 출신이고, 지금은 리뷰어로 후배들의 코드를 함께 다듬어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "3기", "4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/haeyoon1",
    photoUrl: "https://github.com/haeyoon1.png",
    history: [{ cohort: "4기", title: "백엔드 리뷰어" }, { cohort: "3기", title: "운영진 · 백엔드 리드 · 백엔드 리뷰어" }, { cohort: "1기", title: "백엔드 멤버" }],
  },
  {
    id: "임규영",
    name: "임규영",
    affiliation: "2기 FE",
    role: "리뷰어",
    intro: "2기 프론트엔드 출신이고, 지금은 리뷰어로 후배들의 코드를 함께 다듬어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["2기", "3기", "4기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/gxuoo",
    photoUrl: "https://github.com/gxuoo.png",
    history: [{ cohort: "4기", title: "프론트엔드 리뷰어" }, { cohort: "3기", title: "프론트엔드 리드" }, { cohort: "2기", title: "프론트엔드 멤버" }],
  },
  {
    id: "이창희",
    name: "이창희",
    affiliation: "2기 BE",
    role: "리뷰어",
    intro: "2기 백엔드 출신이고, 지금은 리뷰어로 후배들의 코드를 함께 다듬어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["2기", "4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/chxghee",
    photoUrl: "https://github.com/chxghee.png",
    history: [{ cohort: "4기", title: "백엔드 리뷰어" }, { cohort: "2기", title: "백엔드 멤버" }],
  },
  {
    id: "하수한",
    name: "하수한",
    affiliation: "3기 BE",
    role: "리뷰어",
    intro: "3기 백엔드 출신이고, 지금은 리뷰어로 후배들의 코드를 함께 다듬어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["3기", "4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/chemistryx",
    photoUrl: "https://github.com/chemistryx.png",
    history: [{ cohort: "4기", title: "백엔드 리뷰어" }, { cohort: "3기", title: "백엔드 멤버" }],
  },
  {
    id: "이승용",
    name: "이승용",
    affiliation: "창립 멤버",
    role: "멤버",
    intro: "그리디를 처음 만든 창립 멤버예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기", "3기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/kokodak",
    photoUrl: "https://github.com/kokodak.png",
    history: [{ cohort: "3기", title: "회장 · 운영진" }, { cohort: "2기", title: "회장 · 운영진 · 백엔드 리드 · 백엔드 리뷰어" }, { cohort: "1기", title: "회장 · 운영진 · 백엔드 리드 · 백엔드 리뷰어" }, { cohort: "창립", title: "창립 멤버" }],
  },
  {
    id: "원태연",
    name: "원태연",
    affiliation: "창립 멤버",
    role: "멤버",
    intro: "그리디를 처음 만든 창립 멤버예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/TaeyeonRoyce",
    photoUrl: "https://github.com/TaeyeonRoyce.png",
    history: [{ cohort: "2기", title: "운영진 · 백엔드 리뷰어" }, { cohort: "1기", title: "운영진 · 백엔드 리드 · 백엔드 리뷰어" }, { cohort: "창립", title: "창립 멤버" }],
  },
  {
    id: "김주환",
    name: "김주환",
    affiliation: "창립 멤버",
    role: "멤버",
    intro: "그리디를 처음 만든 창립 멤버예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/3Juhwan",
    photoUrl: "https://github.com/3Juhwan.png",
    history: [{ cohort: "2기", title: "운영진 · 백엔드 리드" }, { cohort: "1기", title: "운영진 · 백엔드 리드 · 백엔드 리뷰어" }, { cohort: "창립", title: "창립 멤버" }],
  },
  {
    id: "김준수",
    name: "김준수",
    affiliation: "1기 FE",
    role: "멤버",
    intro: "1기 프론트엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "3기"],
    tracks: ["BE", "FE"],
    githubUrl: "https://github.com/gogo1414",
    photoUrl: "https://github.com/gogo1414.png",
    history: [{ cohort: "3기", title: "운영진 · 백엔드 리뷰어" }, { cohort: "1기", title: "프론트엔드 멤버" }],
  },
  {
    id: "안금서",
    name: "안금서",
    affiliation: "1기 BE",
    role: "멤버",
    intro: "1기 백엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기", "3기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/goldm0ng",
    photoUrl: "https://github.com/goldm0ng.png",
    history: [{ cohort: "3기", title: "백엔드 리드" }, { cohort: "2기", title: "백엔드 리드" }, { cohort: "1기", title: "백엔드 멤버" }],
  },
  {
    id: "홍의민",
    name: "홍의민",
    affiliation: "4기 FE",
    role: "멤버",
    intro: "4기 프론트엔드 멤버로 함께 성장하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/EM-H20",
    photoUrl: "https://github.com/EM-H20.png",
    history: [{ cohort: "4기", title: "프론트엔드 멤버" }],
  },
  {
    id: "김동건",
    name: "김동건",
    affiliation: "4기 FE",
    role: "멤버",
    intro: "4기 프론트엔드 멤버로 함께 성장하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/rahwan10",
    photoUrl: "https://github.com/rahwan10.png",
    history: [{ cohort: "4기", title: "프론트엔드 멤버" }],
  },
  {
    id: "황승준",
    name: "황승준",
    affiliation: "1기 BE",
    role: "멤버",
    intro: "1기 백엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/davidolleh",
    photoUrl: "https://github.com/davidolleh.png",
    history: [{ cohort: "1기", title: "백엔드 멤버" }],
  },
  {
    id: "고규민",
    name: "고규민",
    affiliation: "4기 FE",
    role: "멤버",
    intro: "4기 프론트엔드 멤버로 함께 성장하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/kokunut",
    photoUrl: "https://github.com/kokunut.png",
    history: [{ cohort: "4기", title: "프론트엔드 멤버" }],
  },
  {
    id: "신지훈",
    name: "신지훈",
    affiliation: "1기 BE, 2기 FE",
    role: "멤버",
    intro: "서버를 만들다가 화면이 궁금해져서 프론트엔드로 트랙을 옮겼어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기", "3기"],
    tracks: ["BE", "FE"],
    githubUrl: "https://github.com/developowl",
    photoUrl: "https://github.com/developowl.png",
    history: [{ cohort: "3기", title: "운영진 · 백엔드 리뷰어" }, { cohort: "2기", title: "프론트엔드 멤버" }, { cohort: "1기", title: "백엔드 멤버" }],
  },
  {
    id: "천동현",
    name: "천동현",
    affiliation: "4기 FE",
    role: "멤버",
    intro: "4기 프론트엔드 멤버로 함께 성장하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/realcdh",
    photoUrl: "https://github.com/realcdh.png",
    history: [{ cohort: "4기", title: "프론트엔드 멤버" }],
  },
  {
    id: "김의진",
    name: "김의진",
    affiliation: "1기 BE",
    role: "멤버",
    intro: "1기 백엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/sansan20535",
    photoUrl: "https://github.com/sansan20535.png",
    history: [{ cohort: "1기", title: "백엔드 멤버" }],
  },
  {
    id: "김민욱",
    name: "김민욱",
    affiliation: "4기 BE",
    role: "멤버",
    intro: "4기 백엔드 멤버로 함께 성장하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/hapdaypy",
    photoUrl: "https://github.com/hapdaypy.png",
    history: [{ cohort: "4기", title: "백엔드 멤버" }],
  },
  {
    id: "신지우",
    name: "신지우",
    affiliation: "2기 FE",
    role: "멤버",
    intro: "2기 프론트엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["2기", "3기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/zldn109",
    photoUrl: "https://github.com/zldn109.png",
    history: [{ cohort: "3기", title: "프론트엔드 리드" }, { cohort: "2기", title: "프론트엔드 멤버" }],
  },
  {
    id: "강대현",
    name: "강대현",
    affiliation: "4기 BE",
    role: "멤버",
    intro: "4기 백엔드 멤버로 함께 성장하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/Kdahyn",
    photoUrl: "https://github.com/Kdahyn.png",
    history: [{ cohort: "4기", title: "백엔드 멤버" }],
  },
  {
    id: "정명준",
    name: "정명준",
    affiliation: "4기 BE",
    role: "멤버",
    intro: "4기 백엔드 멤버로 함께 성장하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/htdufhc-bit",
    photoUrl: "https://github.com/htdufhc-bit.png",
    history: [{ cohort: "4기", title: "백엔드 멤버" }],
  },
  {
    id: "이채현",
    name: "이채현",
    affiliation: "4기 BE",
    role: "멤버",
    intro: "4기 백엔드 멤버로 함께 성장하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/chaehyunL",
    photoUrl: "https://github.com/chaehyunL.png",
    history: [{ cohort: "4기", title: "백엔드 멤버" }],
  },
  {
    id: "강동현",
    name: "강동현",
    affiliation: "2기 FE, 3기 BE",
    role: "멤버",
    intro: "화면을 만들다가 서버가 궁금해져서 백엔드로 트랙을 옮겼어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["2기", "3기"],
    tracks: ["BE", "FE"],
    githubUrl: "https://github.com/mintcoke123",
    photoUrl: "https://github.com/mintcoke123.png",
    history: [{ cohort: "3기", title: "백엔드 멤버" }, { cohort: "2기", title: "프론트엔드 멤버" }],
  },
  {
    id: "김하은",
    name: "김하은",
    affiliation: "4기 BE",
    role: "멤버",
    intro: "4기 백엔드 멤버로 함께 성장하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/haeun92e0",
    photoUrl: "https://github.com/haeun92e0.png",
    history: [{ cohort: "4기", title: "백엔드 멤버" }],
  },
  {
    id: "이태규",
    name: "이태규",
    affiliation: "4기 BE",
    role: "멤버",
    intro: "4기 백엔드 멤버로 함께 성장하고 있어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/Cappucciyes",
    photoUrl: "https://github.com/Cappucciyes.png",
    history: [{ cohort: "4기", title: "백엔드 멤버" }],
  },
  {
    id: "허석준",
    name: "허석준",
    affiliation: "2기 BE",
    role: "멤버",
    intro: "2기 백엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["2기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/gjtjrl303",
    photoUrl: "https://github.com/gjtjrl303.png",
    history: [{ cohort: "2기", title: "백엔드 멤버" }],
  },
  {
    id: "전서희",
    name: "전서희",
    affiliation: "2기 BE",
    role: "멤버",
    intro: "2기 백엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["2기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/jeonseohee9",
    photoUrl: "https://github.com/jeonseohee9.png",
    history: [{ cohort: "2기", title: "백엔드 멤버" }],
  },
  {
    id: "김지우",
    name: "김지우",
    affiliation: "2기 BE",
    role: "멤버",
    intro: "2기 백엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["2기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/Ji-Woo-Kim",
    photoUrl: "https://github.com/Ji-Woo-Kim.png",
    history: [{ cohort: "2기", title: "백엔드 멤버" }],
  },
  {
    id: "염지환",
    name: "염지환",
    affiliation: "2기 BE",
    role: "멤버",
    intro: "2기 백엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["2기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/JihwanYeom",
    photoUrl: "https://github.com/JihwanYeom.png",
    history: [{ cohort: "2기", title: "백엔드 멤버" }],
  },
  {
    id: "강건",
    name: "강건",
    affiliation: "3기 FE",
    role: "멤버",
    intro: "3기 프론트엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["3기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/dkr-sjr",
    photoUrl: "https://github.com/dkr-sjr.png",
    history: [{ cohort: "3기", title: "프론트엔드 멤버" }],
  },
  {
    id: "강예령",
    name: "강예령",
    affiliation: "3기 FE",
    role: "멤버",
    intro: "3기 프론트엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["3기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/ehlung",
    photoUrl: "https://github.com/ehlung.png",
    history: [{ cohort: "3기", title: "프론트엔드 멤버" }],
  },
  {
    id: "이고은",
    name: "이고은",
    affiliation: "3기 BE",
    role: "멤버",
    intro: "3기 백엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["3기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/ke-62",
    photoUrl: "https://github.com/ke-62.png",
    history: [{ cohort: "3기", title: "백엔드 멤버" }],
  },
  {
    id: "김태우",
    name: "김태우",
    affiliation: "3기 BE",
    role: "멤버",
    intro: "3기 백엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["3기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/tae-wooo",
    photoUrl: "https://github.com/tae-wooo.png",
    history: [{ cohort: "3기", title: "백엔드 멤버" }],
  },
  {
    id: "서현진",
    name: "서현진",
    affiliation: "3기 BE",
    role: "멤버",
    intro: "3기 백엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["3기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/nonactress",
    photoUrl: "https://github.com/nonactress.png",
    history: [{ cohort: "3기", title: "백엔드 멤버" }],
  },
  {
    id: "김하늘",
    name: "김하늘",
    affiliation: "3기 BE",
    role: "멤버",
    intro: "3기 백엔드 멤버로 함께 성장하며 배웠어요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["3기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/kimsky247-coder",
    photoUrl: "https://github.com/kimsky247-coder.png",
    history: [{ cohort: "3기", title: "백엔드 멤버" }],
  },
  {
    id: "김의천",
    name: "김의천",
    affiliation: "FE",
    role: "든든한 리뷰어",
    intro: "그리디 밖에서 코드 리뷰로 함께하는 든든한 리뷰어예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기", "3기", "4기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/wzrabbit",
    photoUrl: "https://github.com/wzrabbit.png",
    history: [{ cohort: "4기", title: "프론트엔드 리뷰어" }, { cohort: "3기", title: "프론트엔드 리뷰어" }, { cohort: "2기", title: "프론트엔드 리뷰어" }, { cohort: "1기", title: "프론트엔드 리뷰어" }],
  },
  {
    id: "송은우",
    name: "송은우",
    affiliation: "BE",
    role: "든든한 리뷰어",
    intro: "그리디 밖에서 코드 리뷰로 함께하는 든든한 리뷰어예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/be-student",
    photoUrl: "https://github.com/be-student.png",
    history: [{ cohort: "2기", title: "백엔드 리뷰어" }, { cohort: "1기", title: "백엔드 리뷰어" }],
  },
  {
    id: "백경환",
    name: "백경환",
    affiliation: "BE",
    role: "든든한 리뷰어",
    intro: "그리디 밖에서 코드 리뷰로 함께하는 든든한 리뷰어예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기", "3기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/dooboocookie",
    photoUrl: "https://github.com/dooboocookie.png",
    history: [{ cohort: "3기", title: "백엔드 리뷰어" }, { cohort: "2기", title: "백엔드 리뷰어" }, { cohort: "1기", title: "백엔드 리뷰어" }],
  },
  {
    id: "조승현",
    name: "조승현",
    affiliation: "BE",
    role: "든든한 리뷰어",
    intro: "그리디 밖에서 코드 리뷰로 함께하는 든든한 리뷰어예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/BackFoxx",
    photoUrl: "https://github.com/BackFoxx.png",
    history: [{ cohort: "2기", title: "백엔드 리뷰어" }, { cohort: "1기", title: "백엔드 리뷰어" }],
  },
  {
    id: "정다빈",
    name: "정다빈",
    affiliation: "BE",
    role: "든든한 리뷰어",
    intro: "그리디 밖에서 코드 리뷰로 함께하는 든든한 리뷰어예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["1기", "2기", "3기", "4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/70825",
    photoUrl: "https://github.com/70825.png",
    history: [{ cohort: "4기", title: "백엔드 리뷰어" }, { cohort: "3기", title: "백엔드 리뷰어" }, { cohort: "2기", title: "백엔드 리뷰어" }, { cohort: "1기", title: "백엔드 리뷰어" }],
  },
  {
    id: "김민석",
    name: "김민석",
    affiliation: "FE",
    role: "든든한 리뷰어",
    intro: "그리디 밖에서 코드 리뷰로 함께하는 든든한 리뷰어예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["3기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/shackstack",
    photoUrl: "https://github.com/shackstack.png",
    history: [{ cohort: "3기", title: "프론트엔드 리뷰어" }],
  },
  {
    id: "신동훈",
    name: "신동훈",
    affiliation: "BE",
    role: "든든한 리뷰어",
    intro: "그리디 밖에서 코드 리뷰로 함께하는 든든한 리뷰어예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["2기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/shin-mallang",
    photoUrl: "https://github.com/shin-mallang.png",
    history: [{ cohort: "2기", title: "백엔드 리뷰어" }],
  },
  {
    id: "정수영",
    name: "정수영",
    affiliation: "FE",
    role: "든든한 리뷰어",
    intro: "그리디 밖에서 코드 리뷰로 함께하는 든든한 리뷰어예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["3기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/suyoungj",
    photoUrl: "https://github.com/suyoungj.png",
    history: [{ cohort: "3기", title: "프론트엔드 리뷰어" }],
  },
  {
    id: "최혜령",
    name: "최혜령",
    affiliation: "FE",
    role: "든든한 리뷰어",
    intro: "그리디 밖에서 코드 리뷰로 함께하는 든든한 리뷰어예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["3기"],
    tracks: ["FE"],
    githubUrl: "https://github.com/HyeryongChoi",
    photoUrl: "https://github.com/HyeryongChoi.png",
    history: [{ cohort: "3기", title: "프론트엔드 리뷰어" }],
  },
  {
    id: "조상준",
    name: "조상준",
    affiliation: "BE",
    role: "든든한 리뷰어",
    intro: "그리디 밖에서 코드 리뷰로 함께하는 든든한 리뷰어예요. (임시 소개예요. 본인이 보내주면 바꿔요.)",
    cohorts: ["4기"],
    tracks: ["BE"],
    githubUrl: "https://github.com/sangjun121",
    photoUrl: "https://github.com/sangjun121.png",
    history: [{ cohort: "4기", title: "백엔드 리뷰어" }],
  },
];

/** 목록 전체. 운영진 → 리뷰어 → 멤버 → 든든한 리뷰어 순서로 담겨 있어요 */
export async function getMembers(): Promise<Member[]> {
  // TODO: 백엔드 API 연동 (멤버는 서버에서 관리)
  return MEMBERS;
}

/** 프로필 한 명. 없으면 undefined를 줘서 화면이 not-found로 넘겨요 */
export async function getMember(id: string): Promise<Member | undefined> {
  return MEMBERS.find((member) => member.id === id);
}

/** 기수 필터 목록 */
export async function getMemberCohorts(): Promise<string[]> {
  return ["1기", "2기", "3기", "4기"];
}
